#!/bin/sh
# -*- sh -*-
# vim: ft=sh

: << =cut

=head1 NAME

uraniumxd_blocks - Plugin to monitor the number of blocks

=head1 CONFIGURATION

 [uraniumxd*]
    user uraniumx
    env.binary uraniumx-cli
    env.data_dir /var/lib/uraniumx

=head1 AUTHOR

Cedric Felizard

=head1 LICENSE

AGPLv3+

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

BINARY=${binary:-"/usr/bin/uraniumx-cli"}
DATA_DIR=${data_dir:-"/var/lib/uraniumx"}

if [ "$1" = "autoconf" ]; then
    autoconf="yes"

    command -v $BINARY >/dev/null || autoconf="no"

    echo $autoconf
    exit 0
fi

if [ "$1" = "config" ]; then
    echo 'graph_title Block count'
    echo 'graph_vlabel number of blocks'
    echo 'graph_category uraniumxd'
    echo 'graph_info This graph shows the number of blocks.'
    echo 'uraniumxd_blocks.label blocks'
    echo 'uraniumxd_blocks.info The current number of blocks.'
    exit 0
fi

echo "uraniumxd_blocks.value $($BINARY -datadir=$DATA_DIR getblockcount)"

